source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# Declare your gem's dependencies in admin.gemspec.
# Bundler will treat runtime dependencies like base dependencies, and
# development dependencies will be added by default to the :development group.
gemspec

# Declare any dependencies that are still in development here instead of in
# your gemspec. These might include edge Rails or gems from your path or
# Git. Remember to move these dependencies to your gemspec before releasing
# your gem to rubygems.org.

# To use a debugger
# gem 'byebug', group: [:development, :test]

gem 'account',path: "../account"
gem 'product',path: "../product"

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'rspec-rails'
  # guard detect chang need gem install rb-fsevent
  gem 'guard-rspec', require: false
  gem 'factory_bot_rails'
  gem 'rails-controller-testing'
  gem 'faker'

  gem 'awesome_print'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'pry'
  gem 'railroady'
end

  # gem 'rubyzip', '>= 1.2.1'
  # gem 'axlsx', git: 'https://github.com/randym/axlsx.git', ref: 'c8ac844'
